language: julia

os:
    - linux

julia:
    - 1.0
    - 1.3
    - nightly

branches:
    only:
        - master
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
    email: false

jobs:
    include:
        - stage: "Documentation"
          os: linux
          julia: 1.3
          script:
              - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
              - julia --project=docs/ docs/make.jl
          after_success: skip

after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
